spectatorChatPrefix: "&7[&cSpec&7] &f"  # Prefixo do chat de espectadores
specJoinWhenFull: false  # Permitir que jogadores entrem como espectadores quando o servidor estiver cheio pelo /maxplayers

maxPlayers: 10

#lista de mobs que sao ignorados pelo pvm
pvmWhiteList:
  # - "ZOMBIE" [exemplo]


# Configurações de eventos
events:
  build: true
  pvp: true
  chat: true
  drop: true
  pickup: true
  damage: true
  interact: true

  pvm: true
  hck: false
  hcd: false

  specchat: false
  specchatbypass: false
  specchatpublic: false

  maxplayers: false

# configurações de bypass
bypass:
  build: []
  pvp: []
  chat: []
  drop: []
  pickup: []
  damage: []
  interact: []

  pvm: []
  hck: []
  hcd: []

  specchat: []
  specchatbypass: []
  specchatpublic: []

  maxplayers: []

# opção para salvar automaticamente as alterações dos events
autoSaveEventChanges: false
# Opção para salvar automaticamente as alterações da lista de bypass
autoSaveBypassChanges: false